### ISSUE TITLE
Use cypress visual regression test to check after upgrade javascript libraries

### ISSUE THREAD

**Issue by uniqueck** [asciidoctor/asciidoctor-chart#33]
We need a solution to check, after an upgrade of the used javascript libraries, if anything is fine and looks like before this upgrade.

I think a good start are these pages:

* https://cypress.io
* https://docs.cypress.io/guides/tooling/visual-testing#Functional-vs-visual-testing
* https://www.lambdatest.com/blog/cypress-visual-regression-testing/
* https://github.com/mjhea0/cypress-visual-regression

**Comment by Mogztter** [comment]
I think that's good idea 👍🏻 
I had a great experience with Cypress so far, so feel free to open a pull request. If you are not familiar with Cypress, I can set up an initial test?

Let me know how you want to proceed.
