### ISSUE TITLE
New Release

### ISSUE THREAD

**Issue by B3nedikt** [asciidoctor/asciidoctor-chart#38]
Hi, can you please create a new release for rubygems. The last one is two years old. If you are running short on time I could help out as a maintainer :)

**Comment by Mogztter** [comment]
Hey, sure!
The first thing we need to do is add the missing entries in the CHANGELOG.adoc

https://github.com/asciidoctor/asciidoctor-chart/compare/v1.0.0.alpha.1...master

If you want to take care of it that would be great.

**Comment by B3nedikt** [comment]
Done with [#39] :)

**Comment by ggrossetie** [comment]
Thanks for your help!
Version 1.0.0 is now available on https://rubygems.org/gems/asciidoctor-chart/versions/1.0.0

**Comment by B3nedikt** [comment]
You're welcome :)
