### ISSUE TITLE
Request : Allowing relative width specified for the generated graphs

### ISSUE THREAD

**Issue by jpminnovation** [asciidoctor/asciidoctor-chart#9]
Would it be possible to specify the width of the generated graphs with a relative number (percentage) and not only in pixels ?

I would like to have a definition such as : 

```
chart::sample-data.csv[line,engine="chartjs",width="100%"]
```

Currently, this is not possible on : 

- asciidoctor 2.0.16
- asciidoctor-chart 1.0.0.alpha.1

**Comment by Mogztter** [comment]
As mentioned in #8, Chart.js always uses a width of 100% (and does not support specific width or height)
C3.js seems to only support width and height in pixels.
And finally, Chartist always uses a width of 100%.

Again, if my assumptions are incorrect, feel free to comment.

**Comment by jpminnovation** [comment]
If I don't specify width, it does not scale to 100% per default :
![image](https://user-images.githubusercontent.com/96874654/148077221-46e52e2c-f6d7-42eb-ba9d-308a4b5f7eee.png)

However, if I try to put whatever number for width and height, it is getting "larger" than the case above, but with the problem of overlaping what is below the graph :
![image](https://user-images.githubusercontent.com/96874654/148078138-9362ee29-a2af-4966-b3b8-6c9ad1e6d7e3.png)

So not sure of the 100% default.

Finally, if I do specify width **and** height to 100%, it seems to take the full width (without any relation to the number I do specify, may it be 50% or 100%, but take the full width) : 
![image](https://user-images.githubusercontent.com/96874654/148079024-7fa567d0-3af7-46f4-9f08-0ed041bc502d.png)
